#!/bin/bash

mkdir ~/.config/sway/
mv sway-waybar/sway/config ~/.config/sway/
mkdir ~/.config/waybar/
mv sway-waybar/waybar/config ~/.config/waybar/
mv sway-waybar/waybar/style.css ~/.config/waybar/
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
mv .vimrc ~/
mkdir ~/wallpapers
git config --global user.name "juansgdev"
git config --global user.email "juangomes.profissional@gmail.com"
vim -c 'PlugInstall | CocInstall coc-clangd coc-snippets coc-html coc-emmet coc-tsserver coc-json coc-java coc-css | qall'

echo "Instale o Google-Chrome para sincronizar favoritos em: https://www.google.com/chrome/dr/download/"
echo "Baixe algum live wallpaper do Drive e cole-o na pasta wallpapers: https://drive.google.com/"
echo "Baixe o jdk em: https://www.oracle.com/java/technologies/downloads/"
echo "Em root: Para instalar demais pacotes: apt update -y && apt upgrade -y"
echo "Em root: Para aplicar o sway como compositor gráfico e aplicar as mudanças ao final rode: systemctl set-default multi-user.target && systemctl reboot"
