#!/bin/bash
apt remove firefox
apt install chromium xinit xorg feh vim i3 zsh git
git config --global user.name "juansgdev"
git config --global user.email "juangomes.profissional@gmail.com"
git clone https://github.com/juansgdev/desktop-cfgs.git /home/juan/desktop-cfgs
mv ~/desktop-cfgs/.xinitrc ~/
mv ~/desktop-cfgs/.vimrc ~/
sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
mv ~/desktop-cfgs/.zshrc ~/
mkdir -p ~/.config/i3/
mv ~/desktop-cfgs/config ~/.config/i3/
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qall
mv ~/desktop-cfgs/graphical-environment.service /etc/systemd/system/
systemctl set-default multi-user.target
systemctl enable graphical-environment.service
echo Reinicie o sistema agora para aplicar as mudanças!
